<?php

namespace Packfire\Octurlpus\Drivers\YouTube;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\YouTube\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $this->assertTrue($this->object->peek('http://www.youtube.com/watch?feature=test&v=LBTdJHkAr5A'));
        $this->assertTrue($this->object->peek('http://www.youtu.be/LBTdJHkAr5A'));
        $this->assertFalse($this->object->peek('http://www.youtube.com/really?LBTdJHkAr5A'));
        $this->assertFalse($this->object->peek('http://www.youtube.com/watch?feature=test&a=LBTdJHkAr5A'));
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderFetch(){
        $this->object->peek('http://www.youtube.com/watch?feature=test&v=LBTdJHkAr5A');
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('YouTube', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('video', $data['type']);
    }

}