language: php
php:
  - 5.3
  - 5.3.3
  - 5.4
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - ls
script: phpunit -c phpunit.dist.xml --bootstrap test/loader.php