<?php

namespace Packfire\Octurlpus\Drivers\Vimeo;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\Vimeo\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $urls = array(
            'http://www.vimeo.com/7100569' => true,
            'http://vimeo.com/7100569' => true,
            'https://vimeo.com/samyong/packfire-linux-install' => true,
            'https://vimeo.com/groups/magiclantern/videos/43218777' => true,
            'http://vimeo.com/LBTdJHkAr5A' => false,
            'http://www.google.com/' => false
        );
        
        foreach($urls as $url => $result){
            $this->object->set($url);
            $this->assertEquals($result, $this->object->peek());
        }
    }
    
    /**
     * @covers Provider::fetch
     */
    public function testProviderFetch(){
        $this->object->set('https://vimeo.com/groups/magiclantern/videos/43218777');
        $this->object->peek();
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('Vimeo', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('video', $data['type']);
    }

}