<?php

namespace Packfire\Octurlpus\Drivers\Flickr;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\Flickr\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $this->assertTrue($this->object->peek('http://flickr.com/photos/bees/2362225867/'));
        $this->assertTrue($this->object->peek('http://www.flickr.com/photos/bees/2362225867/'));
        $this->assertTrue($this->object->peek('http://www.flickr.com/photos/potatojunkie/4518379530/'));
        $this->assertFalse($this->object->peek('http://www.flickr.com/'));
        $this->assertFalse($this->object->peek('http://www.youtube.com/'));
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderFetch(){
        $this->object->peek('http://www.flickr.com/photos/potatojunkie/4518379530/');
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('Flickr', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('photo', $data['type']);
    }

}