<?php

namespace Packfire\Octurlpus\Drivers\CollegeHumor;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Packfire\Octurlpus\Drivers\CollegeHumor\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Provider;
    }

    public function testProviderPeek()
    {
        $urls = array(
            'http://www.collegehumor.com/video/6791913/call-me-maybe-parody' => true,
            'http://collegehumor.com/video/6789072/dora-the-explorer-movie-trailer-with-ariel-winter' => true,
            'http://www.collegehumor.com/video/6778520/the-fall-of-pinterest' => true,
            'http://www.collegehumor.com/embed/6799030/conan-new-batman-trailer-is-liberal-anti-romney-propaganda' => false,
            'https://speakerdeck.com/u/edds/p/what-the-flash-photography-introduction' => false,
            'http://www.youtube.com/really?LBTdJHkAr5A' => false,
            'http://example.com' => false
        );

        foreach ($urls as $url => $result) {
            $this->object->set($url);
            $this->assertEquals($result, $this->object->peek());
        }
    }

    /**
     * @covers Provider::fetch
     */
    public function testProviderFetch()
    {
        $this->object->set('http://www.collegehumor.com/video/6778520/the-fall-of-pinterest');
        $this->object->peek();
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('CollegeHumor', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('video', $data['type']);
    }
}
