<?php

namespace Packfire\Octurlpus\Drivers\WordPress;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Packfire\Octurlpus\Drivers\Flickr\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Provider;
    }

    public function testProviderPeek()
    {
        $urls = array(
            'http://en.blog.wordpress.com/2012/07/12/around-the-carousel-again/' => true,
            'http://en.blog.wordpress.com/2012/06/21/with-wordads-my-nintendo-news-turns-hobby-into-budding-business/' => true,
            'http://findinggenuinejoy.wordpress.com/2012/07/10/next-stop-the-olympics/' => true,
            'http://wordpress.com' => false,
            'http://www.wordpress.com/' => false
        );

        foreach ($urls as $url => $result) {
            $this->object->set($url);
            $this->assertEquals($result, $this->object->peek());
        }
    }

    public function testProviderFetch()
    {
        $this->object->set('http://en.blog.wordpress.com/2012/07/12/around-the-carousel-again/');
        $this->object->peek();
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('WordPress.com News', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('link', $data['type']);
    }
}
