<?php

namespace Packfire\Octurlpus\Drivers\Viddler;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\Viddler\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $this->assertTrue($this->object->peek('http://www.viddler.com/v/1646c55'));
        $this->assertTrue($this->object->peek('http://www.viddler.com/explore/cdevroe/videos/424/'));
        $this->assertTrue($this->object->peek('http://viddler.com/v/1646c55'));
        $this->assertTrue($this->object->peek('http://viddler.com/explore/cdevroe/videos/424/'));
        $this->assertFalse($this->object->peek('http://viddier.com/really?LBTdJHkAr5A'));
        $this->assertFalse($this->object->peek('http://www.youtube.com/'));
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderFetch(){
        $this->object->peek('http://www.viddler.com/v/1646c55');
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('Viddler', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('video', $data['type']);
    }

}