<?php

namespace Packfire\Octurlpus\Drivers\WordPress;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\Viddler\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $this->assertTrue($this->object->peek('http://en.blog.wordpress.com/2012/07/12/around-the-carousel-again/'));
        $this->assertTrue($this->object->peek('http://en.blog.wordpress.com/2012/06/21/with-wordads-my-nintendo-news-turns-hobby-into-budding-business/'));
        $this->assertTrue($this->object->peek('http://findinggenuinejoy.wordpress.com/2012/07/10/next-stop-the-olympics/'));
        $this->assertFalse($this->object->peek('http://wordpress.com'));
        $this->assertFalse($this->object->peek('http://www.wordpress.com/'));
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderFetch(){
        $this->object->peek('http://en.blog.wordpress.com/2012/07/12/around-the-carousel-again/');
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('WordPress.com News', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('link', $data['type']);
    }

}