<?php

namespace Packfire\Octurlpus\Drivers\Vimeo;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\Vimeo\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $this->assertTrue($this->object->peek('http://www.vimeo.com/7100569'));
        $this->assertTrue($this->object->peek('http://vimeo.com/7100569'));
        $this->assertTrue($this->object->peek('https://vimeo.com/samyong/packfire-linux-install'));
        $this->assertTrue($this->object->peek('https://vimeo.com/groups/magiclantern/videos/43218777'));
        $this->assertFalse($this->object->peek('http://viddier.com/really?LBTdJHkAr5A'));
        $this->assertFalse($this->object->peek('http://www.google.com/'));
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderFetch(){
        $this->object->peek('https://vimeo.com/groups/magiclantern/videos/43218777');
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('Vimeo', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('video', $data['type']);
    }

}