<?php

namespace Packfire\Octurlpus\Drivers\Gist;

/**
 * Test class for Provider.
 * Generated by PHPUnit on 2012-07-16 at 21:08:48.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packfire\Octurlpus\Drivers\Gist\Provider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Provider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Provider::peek
     */
    public function testProviderPeek(){
        $urls = array(
            'https://gist.github.com/3150021' => true,
            'http://gist.github.com/3150021' => true,
            'https://gist.github.com/3150056' => true,
            'http://gist.github.com/3150056/afa3d493fef02289a108e593ccceac30d546aaee' => true,
            'http://viddier.com/really?LBTdJHkAr5A' => false,
            'http://www.google.com/' => false
        );
        
        foreach($urls as $url => $result){
            $this->object->set($url);
            $this->assertEquals($result, $this->object->peek());
        }
    }
    
    /**
     * @covers Provider::fetch
     */
    public function testProviderFetch(){
        $this->object->set('https://gist.github.com/3150056/afa3d493fef02289a108e593ccceac30d546aaee');
        $this->object->peek();
        $data = $this->object->fetch();
        $this->assertNotEmpty($data);
        $this->assertEquals('Github Gist', $data['provider_name']);
        $this->assertEquals('1.0', $data['version']);
        $this->assertEquals('link', $data['type']);
    }

}